"Filed out from Dolphin Smalltalk 7"!

POINTL subclass: #CvPoint
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CvPoint guid: (GUID fromString: '{5E26A557-1E0C-4D09-A107-4E5B8CC1EF9A}')!
CvPoint comment: ''!
!CvPoint categoriesForClass!Win32-Structs! !
!CvPoint class methodsFor!

defineFields
	"
	self compileDefinition
	"

	super defineFields! !
!CvPoint class categoriesFor: #defineFields!**auto generated**!initializing!public! !

