"Filed out from Dolphin Smalltalk 7"!

Smalltalk at: #OpenCVConstants put: (PoolConstantsDictionary named: #OpenCVConstants)!
OpenCVConstants at: 'CV_32FC1' put: 16r5!
OpenCVConstants at: 'CV_8UC4' put: 16r18!
OpenCVConstants at: 'CV_CN_SHIFT' put: 16r3!
OpenCVConstants at: 'CV_LOAD_IMAGE_ANYCOLOR' put: 16r4!
OpenCVConstants at: 'CV_LOAD_IMAGE_ANYDEPTH' put: 16r2!
OpenCVConstants at: 'CV_LOAD_IMAGE_COLOR' put: 16r1!
OpenCVConstants at: 'CV_LOAD_IMAGE_GRAYSCALE' put: 16r0!
OpenCVConstants at: 'CV_LOAD_IMAGE_UNCHANGED' put: -16r1!
OpenCVConstants at: 'CV_MAT_DEPTH_MASK' put: 16r7!
OpenCVConstants at: 'CV_MAT_MAGIC_VAL' put: 16r42420000!
OpenCVConstants at: 'CV_TM_CCOEFF' put: 16r4!
OpenCVConstants at: 'CV_TM_CCOEFF_NORMED' put: 16r5!
OpenCVConstants at: 'CV_TM_CCORR' put: 16r2!
OpenCVConstants at: 'CV_TM_CCORR_NORMED' put: 16r3!
OpenCVConstants at: 'CV_TM_SQDIFF' put: 16r0!
OpenCVConstants at: 'CV_TM_SQDIFF_NORMED' put: 16r1!
OpenCVConstants at: 'NORM_MINMAX' put: 16r20!
OpenCVConstants shrink!
